const data = {
    products: [
      {
        _id: '1',
        name: 'Boys Stillwater Sherpa 1/4-Zip',
        category: 'Shirts',
        image: ['/images/p1.jpg', '/images/b1-1.jpg', '/images/b1-2.jpg'],
        price: 120,
        countInStock: 10,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        discount: 'Eligible for discount',
        shipping: 126,
        style: '3K001154',
        color: ['gray', 'green'],
        size: ['2T', '3T', '4T',  'S', 'M', 'L', 'XL'],
      },
      {
        _id: '2',
        name: 'Boys Sherpa Full-Zip Jacket',
        category: 'Shirts',
        image: ['/images/p2.jpg'],
        price: 100,
        countInStock: 20,
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Boys Sherpa Vest',
        category: 'Shirts',
        image: ['/images/p3.jpg'],
        price: 220,
        countInStock: 5,
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
        discount: 'False',
        shipping: 125,
        color: ['black'],
        size: ['2T', '3T', '4T', '5', '6', '7', 'S', 'M', 'L', 'XL'],
      },
      {
        _id: '4',
        name: 'Boys Quilted Snap Placket Shep Shirt',
        category: 'Pants',
        image: ['/images/p4.jpg'],
        price: 78,
        countInStock: 15,
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
        discount: 'False',
        shipping: 125,
        color: ['yellow'],
        size: ['2T', '3T', '4T', '5', '6', '7'],
      },
      {
        _id: '5',
        name: 'Boys Stillwater Fleece-Lined Hoodie',
        category: 'Pants',
        image: ['/images/p5.jpg'],
        price: 65,
        countInStock: 5,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
        discount: 'False',
        shipping: 125,
        color: ['white'],
        size: ['2T', '3T', '4T', '5', '6', '7'],
      },
      {
        _id: '6',
        name: 'Boys Harbor Fleece Snap Placket',
        category: 'Pants',
        image: ['/images/p6.jpg'],
        price: 139,
        countInStock: 12,
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
        discount: 'False',
        shipping: 125,
        color: ['blue'],
        size: ['2T', '3T', '4T', '5', '6', '7', 'S', 'M', 'L', 'XL'],
      },
    ],
  };
  export default data;
 